### ISSUE TITLE
Current readme.md suggests minimum macOS is 11, this is wrong and should be 13

### ISSUE THREAD

**Issue by stormychel** [orchetect/SettingsAccess#4]
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

First off thanks for making this!

Now let's nitpick.

Current readme.md suggests minimum macOS is 11, this is wrong because 1.4.0 needs Xcode 15, which only works from macOS 13 on.

I hope this helps!

**Comment by orchetect** [comment]
Xcode 15 is required to compile, yes. Once compiled, the executable can target macOS 11 or higher.

Xcode 15 may only run on macOS 13 but you can still develop for older platforms.

You will notice the Demo project targets macOS 11 and compiles without issue:

![demo-macos-11](https://github.com/orchetect/SettingsAccess/assets/11605557/a0bbdbb9-6490-4b4d-afe5-cd6b351eb631)
